# Generated by Django 4.1.3 on 2022-11-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create_at',
        ),
    ]
